<?php
declare(strict_types=1);

use Loki\Components\Factory\ViewModelFactory;
use Loki\CssUtils\Util\CssClass;
use LokiCheckout\MultiSafepay\ViewModel\Wallet;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 2.0.20 */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var CssClass $css */
/** @var ViewModelFactory $viewModelFactory */
/** @var Wallet $wallet */

$wallet = $viewModelFactory->create(Wallet::class);
$jsUrl = $wallet->getJsUrl('paypal');
//echo $jsUrl;
?>
<script src="<?= $escaper->escapeUrl($jsUrl) ?>"></script>
<div id="paypal-button-container"></div>
